### ISSUE TITLE
Accept others conventions

### ISSUE THREAD

**Issue by wbruno** [coderaiser/changelog-io#1]
Hi!

What you think about accept others conventions like:
add:
remove:

Or event accept everything but `Merge pull request`

?

**Comment by coderaiser** [comment]
You mean everything between tags? It's interesting idea. I'll think about it.

**Comment by coderaiser** [comment]
> What you think about accept others conventions like:
> add:
> remove:

This could be solved with:

``` sh
git log v1.0.0..HEAD --pretty=format:"- %s" --grep="add"
git log v1.0.0..HEAD --pretty=format:"- %s" --grep="remove"
```

> Or event accept everything but Merge pull request

This could be solved with help of [--invert-grep](https://git-scm.com/docs/git-log):

``` sh
git log v1.0.0..HEAD --pretty=format:"- %s" --invert-grep --grep="Merge pull request"
```

I'll think about it when I'll have time.
